FROM nasqueron/nginx-php7-fpm:latest
RUN apt-get update && apt-get install -y dos2unix
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY ./service/nginx /var/service/nginx/run
RUN dos2unix /var/service/nginx/run && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*
RUN chmod +x /var/service/nginx/run
COPY ./web_assets/www /usr/share/nginx/html